# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'issueTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.4'
pod 'SwiftLint'
  # Pods for issueTracker
end

target 'issueTrackerTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.4'
pod 'SwiftLint'
  # Pods for issueTracker

end

