# This is a basic workflow to help you get started with Actions

name: issue-tracker

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the team-06 branch
  push:
    branches: [ BE-dev ]
  pull_request:
    branches: [ BE-dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8 
        uses: actions/setup-java@v1 
        with: 
          java-version: 1.8 
      
      - name: Set property
        run: echo ${{ secrets.JASYPT_PASSWORD }} >> application.properties
        shell: bash
        working-directory: ./BE/
          
      - name: Grant execute permission for gradlew 
        run: chmod +x gradlew 
        shell: bash 
        working-directory: ./BE
        
      - name: Build with Gradle 
        run: ./gradlew build -x test 
        shell: bash
        working-directory: ./BE/src/main/resources
        
      - name: Configure AWS credentials 
        uses: aws-actions/configure-aws-credentials@v1 
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ap-northeast-2
        
      - name: Upload to S3 
        run: aws s3 cp ./issue-tracker-0.0.1-SNAPSHOT.jar s3://issue-tracker-jane-eno/issue-tracker.jar
        working-directory: BE/build/libs
